#game options/settings
TITLE = "HEIA Run"
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 460
STAGE_WIDTH = 5000
START_SCROLL_X = DISPLAY_WIDTH / 2
FPS = 60
BOSS_WORLD_NUMBER = 4
WORLD_WITH_TRANSPARENT_BLOCKS = 0
NB_OF_MONSTERS = 15
MONSTER_WIDTH = 100
MONSTER_GAME_POSITION = 130
BOSS_LIFES = 10
BOSS_TIME_THROW = 2000
FINAL_BOSS_WIDTH = 214
FINAL_BOSS_HEIGHT = 156
BOSS_BULLET_DOWN = 110
CONGRATULATIONS_TEXT = "Congratulations ! You won your bachelor !"
CONGRATULATIONS_INFO = "Press space key to return to the main menu"

#menu title options

NEW_GAME_POS = (DISPLAY_WIDTH /2 -150, DISPLAY_HEIGHT /2-45)
LOAD_GAME_POS = (DISPLAY_WIDTH /2 -150, DISPLAY_HEIGHT /2 + 30)
SOUND_MUTE_POS = (DISPLAY_WIDTH /2 -52, DISPLAY_HEIGHT /2 +138)

SND_IMG_SIZE = (70,50)

#Player properties
PLAYER_ACC = 1
PLAYER_FRICTION = -0.15
PLAYER_GRAV = 0.98
PLAYER_JUMP = 25 #velocity when the player jump
PLAYER_SMALL_JUMP = 5 #velocity if we release the K_UP early
PLAYER_HOLE_KILL = 455

#Blocks properties
BLOCK_WIDTH = 150
BLOCK_HEIGHT = 79
HOLES_PROB = 10 # percent

#Sprite properties
PLAYER_WIDTH = 60
PLAYER_HEIGHT = 80

BOSS_POS_X_RIGHT = DISPLAY_WIDTH -220
BOSS_POS_Y_RIGHT = DISPLAY_HEIGHT - BLOCK_HEIGHT
BOSS_POS_X_LEFT = 30
BOSS_POS_Y_LEFT = BOSS_POS_Y_RIGHT

BOSS_BULLET_WIDTH = 60
BOSS_BULLET_HEIGHT = 30


SIGN_WIDTH = 79
SIGN_HEIGHT = 79

LIFE_WIDTH = 30
LIFE_HEIGHT = 30
LIFE_POS_X = 10
LIFE_POS_Y = 8

BULLET_WIDTH = 35
BULLET_HEIGHT = 35
BULLET_SPEED = 10
BOSS_BULLET_SPEED = 5

#define colors
WHITE = (255,255,255)
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
YELLOW = (255,255,0)


#Paths
IMG_PATH = './img/'
IMG_BLOCK_PATH = './img/blocks/'
IMG_PLAYER_PATH = './img/player/'
IMG_BULLET_PATH = './img/bullets/'
IMG_MONSTER_PATH = './img/monsters/'
IMG_BOSS_PATH = './img/boss/'
SND_PATH = './sounds/'

